# Generated by Django 5.1.2 on 2024-12-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
