# Generated by Django 5.1.2 on 2024-12-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_vendorprofile_business_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
