# Generated by Django 5.1.2 on 2024-12-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_vendorprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
