# Generated by Django 5.1.2 on 2024-11-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(null=True)),
                ('image_url', models.URLField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(null=True)),
                ('icon_url', models.URLField(null=True)),
            ],
        ),
    ]
