# Generated by Django 5.1.2 on 2025-01-09 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventry.discount'),
        ),
    ]
