# Generated by Django 5.1.2 on 2024-11-30 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customerprofile'),
        ),
        migrations.AlterField(
            model_name='service',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.vendorprofile'),
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_status', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Archived', 'Archived')], default='Active', max_length=50)),
                ('room_type', models.CharField(choices=[('Customer', 'Customer'), ('Vendor', 'Vendor'), ('Admin', 'Admin')], default='Customer', max_length=50)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.adminprofile')),
                ('user_id1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.vendorprofile')),
                ('user_id2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_content', models.TextField(null=True)),
                ('message_type', models.CharField(choices=[('Text', 'Text'), ('Image', 'Image'), ('Video', 'Video'), ('Audio', 'Audio'), ('File', 'File')], default='Text', max_length=50)),
                ('sent_at', models.DateTimeField(null=True)),
                ('read_at', models.DateTimeField(null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chatroom')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
