# Generated by Django 5.1.2 on 2024-12-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_event_user_alter_service_user_chatroom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmedia',
            name='media_url',
        ),
        migrations.AddField(
            model_name='eventmedia',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='event_media/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='icon_url',
            field=models.ImageField(blank=True, null=True, upload_to='business/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='business/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesstype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesstype',
            name='icon_url',
            field=models.ImageField(blank=True, null=True, upload_to='business_types/'),
        ),
        migrations.AlterField(
            model_name='businesstype',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='business_types/'),
        ),
        migrations.AlterField(
            model_name='businesstype',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventmedia',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
