# Generated by Django 5.1.2 on 2024-12-25 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_event_budget_alter_event_business_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='user',
            new_name='vendor',
        ),
    ]
