# Generated by Django 5.1.2 on 2024-12-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_user_service_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventservice',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
