# Generated by Django 5.1.2 on 2024-12-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_eventservice_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='currency',
            field=models.CharField(choices=[('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('AUD', 'AUD'), ('CAD', 'CAD'), ('JPY', 'JPY'), ('RUB', 'RUB'), ('KRW', 'KRW'), ('CHF', 'CHF'), ('BRL', 'BRL'), ('CNY', 'CNY'), ('HKD', 'HKD'), ('MXN', 'MXN'), ('NZD', 'NZD'), ('PHP', 'PHP'), ('SGD', 'SGD'), ('THB', 'THB'), ('TRY', 'TRY'), ('VND', 'VND'), ('ZAR', 'ZAR'), ('PKR', 'PKR'), ('AED', 'AED')], default='PKR', max_length=3),
        ),
    ]
