# Generated by Django 5.1.2 on 2024-12-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_event_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='maximum_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='minimum_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
