# Generated by Django 5.1.2 on 2024-12-28 09:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_event_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='service',
        ),
        migrations.AddField(
            model_name='messages',
            name='attachment_url',
            field=models.URLField(blank=True, help_text='URL for the attached file or media.', null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='delivery_status',
            field=models.CharField(choices=[('Sent', 'Sent'), ('Delivered', 'Delivered'), ('Read', 'Read')], default='Sent', help_text='Status of the message delivery.', max_length=20),
        ),
        migrations.AddField(
            model_name='messages',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Indicates if the message has been deleted.'),
        ),
        migrations.AddField(
            model_name='messages',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Indicates if the message has been read.'),
        ),
        migrations.AddField(
            model_name='messages',
            name='is_urgent',
            field=models.BooleanField(default=False, help_text='Marks if the message is urgent.'),
        ),
        migrations.AddField(
            model_name='messages',
            name='parent_message',
            field=models.ForeignKey(blank=True, help_text='Reference to the parent message in case of replies.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='core.messages'),
        ),
        migrations.AddField(
            model_name='messages',
            name='receiver_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.chatroom'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messages',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
