# Generated by Django 5.1.2 on 2024-12-29 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_adminprofile_id_alter_customerprofile_id'),
        ('core', '0012_remove_reviews_service_messages_attachment_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.event'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.service'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.vendorprofile'),
        ),
    ]
