# Generated by Django 5.1.2 on 2024-12-31 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_reviews_event_reviews_service_reviews_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
    ]
