# Generated by Django 5.1.2 on 2025-01-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='name',
            field=models.CharField(default='Chat Room', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='event/'),
        ),
    ]
