# Generated by Django 5.1.2 on 2024-11-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_acgtive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
