# Generated by Django 5.1.2 on 2024-12-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry', '0002_rename_is_acgtive_category_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
