# Generated by Django 5.1.2 on 2024-12-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry', '0003_alter_promotion_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='promotions/'),
        ),
    ]
