# Generated by Django 5.1.2 on 2024-12-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry', '0004_alter_promotion_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='discount/'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='subcategories/'),
        ),
    ]
