# Generated by Django 5.1.2 on 2024-12-12 06:43

import inventry.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry', '0006_alter_discount_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to='promotions/videos/', validators=[inventry.validator.validate_video_file]),
        ),
    ]
