# Generated by Django 5.1.2 on 2024-12-17 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
        ('core', '0005_remove_eventmedia_event_eventmedia_event_service_and_more'),
        ('inventry', '0008_alter_promotion_name_alter_promotion_vendor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventry.promotion'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.service'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='vendor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.vendorprofile'),
        ),
    ]
