# Generated by Django 5.1.2 on 2024-12-31 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry', '0009_alter_discount_promotion_alter_discount_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
