# Generated by Django 5.1.2 on 2024-12-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry', '0011_remove_category_description_category_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
