# Generated by Django 5.1.4 on 2025-01-06 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGetway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('api_key', models.TextField(null=True)),
                ('secret_key', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_url', models.URLField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('transaction_fee', models.FloatField(blank=True, null=True)),
                ('additional_config', models.TextField(blank=True, null=True)),
                ('supported_currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('AUD', 'AUD'), ('CAD', 'CAD'), ('JPY', 'JPY'), ('RUB', 'RUB'), ('KRW', 'KRW'), ('CHF', 'CHF'), ('BRL', 'BRL'), ('CNY', 'CNY'), ('HKD', 'HKD'), ('MXN', 'MXN'), ('NZD', 'NZD'), ('PHP', 'PHP'), ('SGD', 'SGD'), ('THB', 'THB'), ('TRY', 'TRY'), ('VND', 'VND'), ('ZAR', 'ZAR'), ('PKR', 'PKR'), ('AED', 'AED')], default='PKR', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_amount', models.FloatField(default=0.0)),
                ('currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('AUD', 'AUD'), ('CAD', 'CAD'), ('JPY', 'JPY'), ('RUB', 'RUB'), ('KRW', 'KRW'), ('CHF', 'CHF'), ('BRL', 'BRL'), ('CNY', 'CNY'), ('HKD', 'HKD'), ('MXN', 'MXN'), ('NZD', 'NZD'), ('PHP', 'PHP'), ('SGD', 'SGD'), ('THB', 'THB'), ('TRY', 'TRY'), ('VND', 'VND'), ('ZAR', 'ZAR'), ('PKR', 'PKR'), ('AED', 'AED')], default='PKR', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED'), ('REFUNDED', 'REFUNDED')], default='PENDING', max_length=20)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('discount_amount', models.FloatField(default=0.0)),
                ('tax_amount', models.FloatField(default=0.0)),
                ('note', models.TextField(blank=True, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customerprofile')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.vendorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('AUD', 'AUD'), ('CAD', 'CAD'), ('JPY', 'JPY'), ('RUB', 'RUB'), ('KRW', 'KRW'), ('CHF', 'CHF'), ('BRL', 'BRL'), ('CNY', 'CNY'), ('HKD', 'HKD'), ('MXN', 'MXN'), ('NZD', 'NZD'), ('PHP', 'PHP'), ('SGD', 'SGD'), ('THB', 'THB'), ('TRY', 'TRY'), ('VND', 'VND'), ('ZAR', 'ZAR'), ('PKR', 'PKR'), ('AED', 'AED')], default='PKR', max_length=3)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='SUCCESS', max_length=20)),
                ('transcation_date', models.DateTimeField(blank=True, null=True)),
                ('getway_response', models.JSONField(blank=True, null=True)),
                ('paymment_method', models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('CASH_ON_DELIVERY', 'Cash On Delivery')], default='CREDIT_CARD', max_length=100)),
                ('retry_count', models.IntegerField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.order')),
                ('payment_getway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.paymentgetway')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('AUD', 'AUD'), ('CAD', 'CAD'), ('JPY', 'JPY'), ('RUB', 'RUB'), ('KRW', 'KRW'), ('CHF', 'CHF'), ('BRL', 'BRL'), ('CNY', 'CNY'), ('HKD', 'HKD'), ('MXN', 'MXN'), ('NZD', 'NZD'), ('PHP', 'PHP'), ('SGD', 'SGD'), ('THB', 'THB'), ('TRY', 'TRY'), ('VND', 'VND'), ('ZAR', 'ZAR'), ('PKR', 'PKR'), ('AED', 'AED')], default='PKR', max_length=3)),
                ('status', models.CharField(choices=[('PAID', 'PAID'), ('UNPAID', 'UNPAID')], default='UNPAID', max_length=20)),
                ('paymment_method', models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('CASH_ON_DELIVERY', 'Cash On Delivery')], default='CREDIT_CARD', max_length=100)),
                ('transaction_refrence', models.CharField(blank=True, max_length=200, null=True)),
                ('refund_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('getway_response', models.JSONField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.order')),
                ('payment_getway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.paymentgetway')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.transaction')),
            ],
        ),
    ]
