# Generated by Django 5.1.3 on 2024-11-15 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_amount', models.FloatField(null=True)),
                ('currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('AUD', 'AUD'), ('CAD', 'CAD'), ('JPY', 'JPY'), ('RUB', 'RUB'), ('KRW', 'KRW'), ('CHF', 'CHF'), ('BRL', 'BRL'), ('CNY', 'CNY'), ('HKD', 'HKD'), ('MXN', 'MXN'), ('NZD', 'NZD'), ('PHP', 'PHP'), ('SGD', 'SGD'), ('THB', 'THB'), ('TRY', 'TRY'), ('VND', 'VND'), ('ZAR', 'ZAR'), ('PKR', 'PKR'), ('AED', 'AED')], default='PKR', max_length=3)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('X', 'Cancelled'), ('R', 'Refunded')], default='P', max_length=20)),
                ('shipping_address', models.TextField(null=True)),
                ('billing_address', models.TextField(null=True)),
                ('discount_amount', models.FloatField(null=True)),
                ('tax_amount', models.FloatField(null=True)),
                ('note', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentGetway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('api_key', models.TextField(null=True)),
                ('secret_key', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_url', models.URLField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('transaction_fee', models.FloatField(null=True)),
                ('additional_config', models.TextField(null=True)),
                ('supported_currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('AUD', 'AUD'), ('CAD', 'CAD'), ('JPY', 'JPY'), ('RUB', 'RUB'), ('KRW', 'KRW'), ('CHF', 'CHF'), ('BRL', 'BRL'), ('CNY', 'CNY'), ('HKD', 'HKD'), ('MXN', 'MXN'), ('NZD', 'NZD'), ('PHP', 'PHP'), ('SGD', 'SGD'), ('THB', 'THB'), ('TRY', 'TRY'), ('VND', 'VND'), ('ZAR', 'ZAR'), ('PKR', 'PKR'), ('AED', 'AED')], default='PKR', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField(null=True)),
                ('currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('AUD', 'AUD'), ('CAD', 'CAD'), ('JPY', 'JPY'), ('RUB', 'RUB'), ('KRW', 'KRW'), ('CHF', 'CHF'), ('BRL', 'BRL'), ('CNY', 'CNY'), ('HKD', 'HKD'), ('MXN', 'MXN'), ('NZD', 'NZD'), ('PHP', 'PHP'), ('SGD', 'SGD'), ('THB', 'THB'), ('TRY', 'TRY'), ('VND', 'VND'), ('ZAR', 'ZAR'), ('PKR', 'PKR'), ('AED', 'AED')], default='PKR', max_length=3)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('X', 'Cancelled'), ('R', 'Refunded')], default='P', max_length=20)),
                ('transcation_date', models.DateTimeField(null=True)),
                ('getway_response', models.JSONField(null=True)),
                ('paymment_method', models.CharField(choices=[('CC', 'Credit Card'), ('DC', 'Debit Card'), ('BT', 'Bank Transfer'), ('COD', 'Cash On Delivery')], default='CC', max_length=100)),
                ('retry_count', models.IntegerField(null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.order')),
                ('payment_getway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.paymentgetway')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField(null=True)),
                ('payment_date', models.DateTimeField(null=True)),
                ('currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('AUD', 'AUD'), ('CAD', 'CAD'), ('JPY', 'JPY'), ('RUB', 'RUB'), ('KRW', 'KRW'), ('CHF', 'CHF'), ('BRL', 'BRL'), ('CNY', 'CNY'), ('HKD', 'HKD'), ('MXN', 'MXN'), ('NZD', 'NZD'), ('PHP', 'PHP'), ('SGD', 'SGD'), ('THB', 'THB'), ('TRY', 'TRY'), ('VND', 'VND'), ('ZAR', 'ZAR'), ('PKR', 'PKR'), ('AED', 'AED')], default='PKR', max_length=3)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('X', 'Cancelled'), ('R', 'Refunded')], default='P', max_length=20)),
                ('paymment_method', models.CharField(choices=[('CC', 'Credit Card'), ('DC', 'Debit Card'), ('BT', 'Bank Transfer'), ('COD', 'Cash On Delivery')], default='CC', max_length=100)),
                ('transaction_refrence', models.CharField(max_length=200, null=True)),
                ('refund_amount', models.FloatField(null=True)),
                ('getway_response', models.JSONField(null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.order')),
                ('payment_getway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.paymentgetway')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.transaction')),
            ],
        ),
    ]
