# Generated by Django 5.1.2 on 2025-01-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgetway',
            name='additional_config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentgetway',
            name='api_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentgetway',
            name='base_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentgetway',
            name='secret_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentgetway',
            name='transaction_fee',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
