# Generated by Django 5.1.2 on 2025-01-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_paymentgetway_additional_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgetway',
            name='additional_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
